### PR TITLE
add CMake support.

### PR DESCRIPTION
**Pull request by tearsofphoenix**

### CODE REVIEW

**Comment by exaexa** [comment]
Hi,

Thanks for the contribution. There are 2 problems:

First, the produced executable should be named `ccr` not `codecrypt`.

Second, would it also be possible to check for `readpassphrase` function from libBSD (and setting flags accordingly) so that the compile warning about defaulting to `getpass()` is not produced?

This:
```
[ 42%] Building CXX object CMakeFiles/codecrypt.dir/src/pwrng.cpp.o
/home/exa/work/codecrypt/src/pwrng.cpp:31:2: warning: #warning "Falling back to getpass(3), which is marked obsolete!" [-Wcpp]
 #warning "Falling back to getpass(3), which is marked obsolete!"
  ^~~~~~~
```

You may find the relevant logic here:
https://github.com/exaexa/codecrypt/blob/master/configure.ac#L58-L73

Anyway, please continue working rebased to 'cmake' master of codecrypt repo.

**Comment by exaexa** [comment]
Looks better (though it would be much nicer to actually *check* for readpassphrase presence, and not rely on the (false) presumption that "all unixes have bsd/readpassphrase.h".

Anyway, I just noticed that the resulting `ccr` is compiled without crypto++ support (thus, no SHA-family hashes etc.). Probably not a problem but it would be nice to also include the check.

**Comment by tearsofphoenix** [comment]
@exaexa  now, add real check for both libraries. No need to check on mac because it has
`readpassphrase.h`. Tested on macOS High Sierra 10.13.2 & Ubuntu 16.04.

**Comment by exaexa** [comment]
OK, now it works just right! Accepted&thanks!

**Pull request closed without merging**
